[[watch]]
# whoa.........
name = "caretaker"
path = "/home/greg/.dotfiles/caretaker.toml"
command = "systemctl --user restart caretaker"

[[watch]]
name = "polybar"
path = "/home/greg/.dotfiles/polybar"
command = "systemctl --user restart polybar"

[[watch]]
name = "i3"
path = "/home/greg/.dotfiles/i3"
command = "/home/greg/.dotfiles/bin/theme"

[[watch]]
name = "nvim"
path = "/home/greg/.dotfiles/nvim"
command = "nvim-ctrl \"luafile ~/.dotfiles/nvim/init.lua\""

[[watch]]
name = "gtk"
path = "/home/greg/.dotfiles/xsettingsd/*.conf"
command = "systemctl --user reload-or-restart xsettingsd"

[[watch]]
name = "systemd units"
path = "/home/greg/.dotfiles/systemd/user"
command = "systemctl --user daemon-reload"
