# vi ft=sh

#xrandr --auto
#xrandr --setprovideroutputsource modesetting NVIDIA-0

systemctl --user import-environment DISPLAY

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

eval $(dbus-launch --sh-syntax)
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

exec i3
