# vi ft=sh

eval $(dbus-launch --sh-syntax)

systemctl --user import-environment DISPLAY DBUS_SESSION_BUS_ADDRESS

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

exec i3
