#!/bin/fish

if xrandr -q | rg "HDMI-1-1 connected"
    bspc wm -O eDP-1-1 HDMI-1-1
    bspc monitor eDP-1-1 -d 1 3 5 7 9
    bspc monitor HDMI-1-1 -d 2 4 6 8 10
else
    bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 10
end

bspc config border_width 6
bspc config normal_border_color "#444444"
bspc config focused_border_color "#ffffff"

bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config bottom_padding 0
bspc config -m eDP-1-1 bottom_padding (sd-dev -f ms '.*height = (\d+).*' '$1' <  ~/.dotfiles/polybar/config)

# pointer
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod1
bspc config pointer_action1 resize_corner
