zstyle :plugin:fast-syntax-highlighting theme "theme"
typeset -g FAST_THEME_NAME="theme"
: ${FAST_HIGHLIGHT_STYLES[themedefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[themeunknown-token]:=fg=124,bold}
: ${FAST_HIGHLIGHT_STYLES[themereserved-word]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[themealias]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themesuffix-alias]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themebuiltin]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themefunction]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themecommand]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themeprecommand]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themecommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[themehashed-command]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themepath]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[themepath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[themeglobbing]:=fg=220}
: ${FAST_HIGHLIGHT_STYLES[themeglobbing-ext]:=fg=225}
: ${FAST_HIGHLIGHT_STYLES[themehistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[themesingle-hyphen-option]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[themedouble-hyphen-option]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[themeback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[themesingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[themedouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[themedollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[themeback-or-dollar-double-quoted-argument]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[themeback-dollar-quoted-argument]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[themeassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[themeredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[themecomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[themevariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[thememathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[thememathnum]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[themematherr]:=fg=124}
: ${FAST_HIGHLIGHT_STYLES[themeassign-array-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themefor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[themefor-loop-number]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[themefor-loop-operator]:=fg=147}
: ${FAST_HIGHLIGHT_STYLES[themefor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themeexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[themehere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[themehere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[themehere-string-var]:=fg=185,bg=19}
: ${FAST_HIGHLIGHT_STYLES[themesecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[themecase-input]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themecase-parentheses]:=fg=116}
: ${FAST_HIGHLIGHT_STYLES[themecase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[themecorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[themeincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[themesubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[themepath-to-dir]:=fg=208,underline}
: ${FAST_HIGHLIGHT_STYLES[themepaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[themebracket-level-1]:=fg=115}
: ${FAST_HIGHLIGHT_STYLES[themebracket-level-2]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[themebracket-level-3]:=fg=220}
: ${FAST_HIGHLIGHT_STYLES[themeglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[themesubcommand]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[themesingle-sq-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themedouble-sq-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[themedouble-paren]:=fg=146}
