zstyle :plugin:fast-syntax-highlighting theme "clean"
typeset -g FAST_THEME_NAME="clean"
: ${FAST_HIGHLIGHT_STYLES[cleandefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleanunknown-token]:=fg=124,bold}
: ${FAST_HIGHLIGHT_STYLES[cleanreserved-word]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[cleanalias]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleansuffix-alias]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanbuiltin]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanfunction]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleancommand]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanprecommand]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleancommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleanhashed-command]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanpath]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[cleanpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[cleanglobbing]:=fg=220}
: ${FAST_HIGHLIGHT_STYLES[cleanglobbing-ext]:=fg=225}
: ${FAST_HIGHLIGHT_STYLES[cleanhistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[cleansingle-hyphen-option]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[cleandouble-hyphen-option]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[cleanback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleansingle-quoted-argument]:=fg=147}
: ${FAST_HIGHLIGHT_STYLES[cleandouble-quoted-argument]:=fg=147}
: ${FAST_HIGHLIGHT_STYLES[cleandollar-quoted-argument]:=fg=147}
: ${FAST_HIGHLIGHT_STYLES[cleanback-or-dollar-double-quoted-argument]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[cleanback-dollar-quoted-argument]:=fg=185}
: ${FAST_HIGHLIGHT_STYLES[cleanassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleanredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleancomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[cleanvariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleanmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[cleanmathnum]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[cleanmatherr]:=fg=124}
: ${FAST_HIGHLIGHT_STYLES[cleanassign-array-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[cleanfor-loop-number]:=fg=208}
: ${FAST_HIGHLIGHT_STYLES[cleanfor-loop-operator]:=fg=147}
: ${FAST_HIGHLIGHT_STYLES[cleanfor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleanexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[cleanhere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[cleanhere-string-text]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[cleanhere-string-var]:=fg=185,bg=19}
: ${FAST_HIGHLIGHT_STYLES[cleansecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[cleancase-input]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleancase-parentheses]:=fg=116}
: ${FAST_HIGHLIGHT_STYLES[cleancase-condition]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[cleancorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[cleanincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[cleansubtle-bg]:=bg=17}
: ${FAST_HIGHLIGHT_STYLES[cleanpath-to-dir]:=fg=208,underline}
: ${FAST_HIGHLIGHT_STYLES[cleanpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[cleanbracket-level-1]:=fg=115}
: ${FAST_HIGHLIGHT_STYLES[cleanbracket-level-2]:=fg=177}
: ${FAST_HIGHLIGHT_STYLES[cleanbracket-level-3]:=fg=220}
: ${FAST_HIGHLIGHT_STYLES[cleanglobal-alias]:=bg=19}
: ${FAST_HIGHLIGHT_STYLES[cleansubcommand]:=fg=146}
: ${FAST_HIGHLIGHT_STYLES[cleansingle-sq-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleandouble-sq-bracket]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[cleandouble-paren]:=fg=146}
