-- packer.use({
--     "neovim/nvim-lspconfig",
--     config = function()
--         local lsp = require("lspconfig")
--         lsp.rust_analyzer.setup{}
--         lsp.tsserver.setup{}
--         lsp.terraformls.setup{}
--         lsp.cssls.setup{}
--     end
-- })
-- packer.use({
--     "hrsh7th/nvim-compe",
--     config = function()
--         require'compe'.setup({
--             throttle_time = 300,
--           source = {
--             nvim_lsp = true,
--             nvim_lua = true,
--             path = false,
--
--             buffer = false,
--             calc = false,
--             vsnip = false,
--             treesitter = false
--           }
--         })
--     end
-- })
--
-- packer.use {
--   "folke/lsp-trouble.nvim",
--   requires = "kyazdani42/nvim-web-devicons",
--   config = function()
--     require("trouble").setup {
--     }
--   end
-- }
--
-- packer.use({ 'folke/lsp-colors.nvim' })
